import { NextResponse } from "next/server";
import { generateWithFallback } from "@/lib/ai";

interface Exercise {
  exerciseId: string;
  title: string;
  userAnswer: string;
  aiSolution: string;
}

export async function POST(req: Request) {
  try {
    const { exercises } = await req.json();

    if (!exercises || !Array.isArray(exercises) || exercises.length === 0) {
      return NextResponse.json({ error: "No exercises provided" }, { status: 400 });
    }

    const comparisons: any[] = [];
    let aiDetectedCount = 0;

    for (const exercise of exercises) {
      const prompt = `
Analyze if the student's answer appears to be AI-generated by comparing it to the model answer.

## Exercise Title
${exercise.title}

## Model Answer (Ideal Answer)
${exercise.aiSolution}

## Student's Answer
${exercise.userAnswer}

## Task
Compare the two answers and determine:
1. What is the similarity percentage (0-100)?
2. Does the student's answer appear to be AI-generated or heavily AI-assisted?

Provide your response in JSON format:
{
  "similarity": number (0-100),
  "aiDetected": boolean (true if similarity > 70 OR if answer appears AI-generated),
  "reason": "brief explanation of why you think it's AI or not"
}
`;

      try {
        const result = await generateWithFallback(prompt);
        const parsed = result.parsed || { similarity: 0, aiDetected: false, reason: "Analysis failed" };

        comparisons.push({
          exerciseId: exercise.exerciseId,
          title: exercise.title,
          userAnswer: exercise.userAnswer,
          aiSolution: exercise.aiSolution,
          similarity: parsed.similarity,
          aiDetected: parsed.aiDetected,
          reason: parsed.reason,
        });

        if (parsed.aiDetected) aiDetectedCount++;
      } catch (error) {
        console.error("Comparison error for exercise:", exercise.exerciseId, error);
        comparisons.push({
          exerciseId: exercise.exerciseId,
          title: exercise.title,
          userAnswer: exercise.userAnswer,
          aiSolution: exercise.aiSolution,
          similarity: 0,
          aiDetected: false,
          reason: "Analysis failed",
        });
      }
    }

    return NextResponse.json({
      comparisons,
      aiDetectedCount,
      finalPenalty: aiDetectedCount * 10,
    });
  } catch (error: any) {
    console.error("Compare answers error:", error);
    return NextResponse.json({ error: "Failed to compare answers" }, { status: 500 });
  }
}